"use client";

import { useEffect, useState } from "react";
import { FiChevronDown, FiCpu } from "react-icons/fi";
import { authedFetch, getStoredAuth } from "@/lib/client/api";

export default function AiFixSuggestions({ scanId }: { scanId: string }) {
  const [open, setOpen] = useState(false);
  const [text, setText] = useState<string | null>(null);
  const [state, setState] = useState<"loading" | "ready" | "nokey" | "pending" | "error">(
    "loading",
  );
  const [busy, setBusy] = useState(false);

  async function fetchSuggestions() {
    setState("loading");
    try {
      const auth = getStoredAuth();
      if (!auth) {
        setState("error");
        return;
      }
      const res = await authedFetch(`/api/scan/${scanId}`, { cache: "no-store" });
      const data = await res.json();
      if (!res.ok || !data.success) throw new Error(data.error?.message || "Failed to load scan.");

      const remediation: string | null = data.scan?.aiRemediation ?? null;
      if (remediation) {
        setText(remediation);
        setState("ready");
        return;
      }
      // No stored remediation — check whether AI is configured by probing generation.
      setState("pending");
    } catch {
      setState("error");
    }
  }

  async function generate() {
    setBusy(true);
    try {
      const res = await authedFetch(`/api/scan/${scanId}/ai-fix`, { method: "POST" });
      const data = await res.json();
      if (res.status === 503 || data.error?.code === "AI_NOT_CONFIGURED") {
        setState("nokey");
        return;
      }
      if (!res.ok || !data.success) throw new Error(data.error?.message || "AI generation failed.");
      if (data.unavailable) {
        setState("pending");
        return;
      }
      setText(data.remediation as string);
      setState("ready");
    } catch {
      setState("error");
    } finally {
      setBusy(false);
    }
  }

  useEffect(() => {
    if (open && state === "loading") void fetchSuggestions();
  }, [open, state]);

  return (
    <section className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white/5">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
        className="flex w-full items-center justify-between gap-3 px-6 py-4 text-left"
      >
        <span className="flex items-center gap-2 text-base font-bold text-white">
          <FiCpu className="h-5 w-5 text-primary-400" />
          🤖 AI Fix Suggestions
        </span>
        <FiChevronDown
          className={`h-5 w-5 text-white/60 transition-transform ${open ? "rotate-180" : ""}`}
        />
      </button>

      {open && (
        <div className="border-t border-white/10 px-6 py-4">
          {state === "loading" && <p className="text-sm text-white/60">Loading…</p>}

          {state === "ready" && text && (
            <div className="space-y-2">
              <p className="text-xs uppercase tracking-wide text-white/40">
                Generated by a senior-security-engineer persona · verify before applying
              </p>
              <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-white/85">
                {text}
              </pre>
            </div>
          )}

          {state === "nokey" && (
            <p className="rounded-lg border border-amber-400/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">
              AI feature requires API key. Ask the site owner to configure OPENAI_API_KEY.
            </p>
          )}

          {state === "pending" && (
            <div className="flex flex-col gap-3">
              <p className="text-sm text-white/70">
                AI suggestions have not been generated for this scan yet.
              </p>
              <button
                type="button"
                onClick={() => void generate()}
                disabled={busy}
                className="self-start rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-primary-500 disabled:opacity-60"
              >
                {busy ? "Generating…" : "Generate AI fix suggestions"}
              </button>
            </div>
          )}

          {state === "error" && (
            <p className="text-sm text-white/60">Could not load AI suggestions right now.</p>
          )}
        </div>
      )}
    </section>
  );
}
