import { jsPDF } from "jspdf";
import type { ScanResult, LinkStatus } from "@/types/scan";

const SLATE: [number, number, number] = [15, 23, 42];
const SLATE_LIGHT: [number, number, number] = [100, 116, 139];
const BORDER: [number, number, number] = [203, 213, 225];
const BG_SOFT: [number, number, number] = [241, 245, 249];
const EMERALD: [number, number, number] = [5, 150, 105];
const BLUE: [number, number, number] = [2, 132, 199];
const RED: [number, number, number] = [225, 29, 72];
const RED_BG: [number, number, number] = [255, 241, 242];
const GREEN_BG: [number, number, number] = [236, 253, 245];
const AMBER: [number, number, number] = [180, 83, 9];
const AMBER_BG: [number, number, number] = [255, 251, 235];

const PAGE_BOTTOM = 282;
const CONTACT_LINE =
  "Generated by LeadGuard  |  mohitsikarwar123@gmail.com  |  WhatsApp +91 83070 70605";

function fmtRs(n: number): string {
  return "Rs " + n.toLocaleString("en-IN");
}

function statusColor(s: LinkStatus): [number, number, number] {
  return s === "WORKING" ? EMERALD : RED;
}

export function generateAuditPdf(
  url: string,
  result: ScanResult,
  opts?: { completedAt?: string }
): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  let y = 0;

  const ensureSpace = (needed: number) => {
    if (y + needed > PAGE_BOTTOM) {
      drawFooter(doc);
      doc.addPage();
      y = 16;
    }
  };

  const header = () => {
    doc.setFillColor(...SLATE);
    doc.rect(0, 0, 210, 40, "F");
    doc.setFillColor(16, 185, 129);
    doc.rect(0, 40, 210, 2, "F");

    doc.setTextColor(248, 250, 252);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("LEADGUARD", 15, 17);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(148, 163, 184);
    doc.text("WEBSITE LEAD-LOSS & SECURITY AUDIT", 15, 24);
    doc.text("Free automated scan - every broken contact channel loses paying customers.", 15, 30);

    const dateStr = new Date(opts?.completedAt || Date.now()).toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
    doc.text(`Audit date: ${dateStr}`, 195, 24, { align: "right" });
    y = 50;
  };

  const drawFooter = (d: jsPDF) => {
    d.setFontSize(7.5);
    d.setFont("helvetica", "normal");
    d.setTextColor(148, 163, 184);
    d.text(CONTACT_LINE, 105, 290, { align: "center" });
    d.text(String(d.getNumberOfPages()), 200, 285, { align: "right" });
  };

  header();

  doc.setFillColor(...BG_SOFT);
  doc.roundedRect(15, y - 4, 180, 20, 2.5, 2.5, "F");
  doc.setFontSize(8);
  doc.setTextColor(...SLATE_LIGHT);
  doc.text("AUDITED WEBSITE:", 20, y + 3);
  doc.setFontSize(12.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BLUE);
  const urlShort = url.replace(/^https?:\/\//, "");
  doc.text(doc.splitTextToSize(urlShort, 120)[0], 20, y + 10.5);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...SLATE_LIGHT);
  doc.text(`${result.scanStats.totalLinks} links checked`, 190, y + 3, { align: "right" });
  doc.text(`${result.performance.totalTime}ms scan time`, 190, y + 10, { align: "right" });
  y += 26;

  const cardW = 56;
  const cardY = y;
  const cards: { x: number; label: string; value: string; color: [number, number, number]; bg: [number, number, number] }[] = [
    {
      x: 15,
      label: "HEALTH SCORE",
      value: `${result.score}/100`,
      color: result.score >= 70 ? EMERALD : result.score >= 40 ? AMBER : RED,
      bg: result.score >= 70 ? GREEN_BG : result.score >= 40 ? AMBER_BG : RED_BG,
    },
    {
      x: 77,
      label: "WORKING / BROKEN LINKS",
      value: `${result.scanStats.workingLinks} / ${result.scanStats.brokenLinks}`,
      color: result.scanStats.brokenLinks > 0 ? RED : EMERALD,
      bg: [255, 255, 255],
    },
    {
      x: 139,
      label: "EST. MONTHLY LEAD LOSS",
      value: fmtRs(result.estimatedLoss),
      color: RED,
      bg: RED_BG,
    },
  ];
  for (const c of cards) {
    doc.setFillColor(...c.bg);
    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.4);
    doc.roundedRect(c.x, cardY, cardW, 26, 2.5, 2.5, "FD");
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...SLATE_LIGHT);
    doc.text(c.label, c.x + 5, cardY + 8);
    doc.setFontSize(15);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...c.color);
    doc.text(c.value, c.x + 5, cardY + 19);
  }
  y += 32;
  doc.setFontSize(6.8);
  doc.setTextColor(...SLATE_LIGHT);
  doc.text("*Loss estimate assumes Rs 7,500/month per broken channel. Use our online calculator to adjust for your traffic.", 15, y);
  y += 10;

  if (result.pillars) {
    const p = result.pillars;
    const pillarDefs: { name: string; score: number; issues: number }[] = [
      { name: "LEAD GUARDIAN", score: p.lead.score, issues: p.lead.issueCount },
      { name: "AD SHIELD", score: p.adshield.score, issues: p.adshield.issueCount },
      { name: "SEO SHIELD", score: p.seo.score, issues: p.seo.issueCount },
      { name: "CYBER SHIELD", score: p.cyber.score, issues: p.cyber.issueCount },
    ];
    const pw = 42;
    pillarDefs.forEach((def, idx) => {
      const px = 15 + idx * (pw + 4);
      const col: [number, number, number] =
        def.score >= 90 ? EMERALD : def.score >= 70 ? BLUE : def.score >= 50 ? AMBER : RED;
      doc.setFillColor(...[255, 255, 255]);
      doc.setDrawColor(...BORDER);
      doc.setLineWidth(0.4);
      doc.roundedRect(px, y, pw, 20, 2, 2, "FD");
      doc.setFontSize(5.6);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...SLATE_LIGHT);
      doc.text(def.name, px + 3.5, y + 5.5);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(...col);
      doc.text(`${Math.round(def.score)}`, px + 3.5, y + 14);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(5.8);
      doc.setTextColor(...SLATE_LIGHT);
      doc.text(def.issues > 0 ? `${def.issues} finding(s)` : "all clear", px + 13.5, y + 14);
    });
    y += 26;
  }

  if (result.security && result.security.status !== "CLEAN") {
    ensureSpace(46);
    const danger = result.security.status === "DANGER";
    const secBg: [number, number, number] = danger ? RED_BG : AMBER_BG;
    const secFg: [number, number, number] = danger ? RED : AMBER;

    doc.setFillColor(...secBg);
    doc.setDrawColor(...secFg);
    doc.roundedRect(15, y, 180, 12, 2, 2, "FD");
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...secFg);
    doc.text(`SECURITY CHECK: ${result.security.status}`, 20, y + 7.5);
    y += 16;

    for (const f of result.security.findings) {
      const lines = doc.splitTextToSize(f.detail, 168) as string[];
      ensureSpace(lines.length * 4 + 14);
      doc.setFontSize(8.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...secFg);
      doc.circle(18, y + 1.2, 0.9, "F");
      doc.text(f.type.replace(/_/g, " ").toUpperCase(), 22, y + 2.5);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(51, 65, 85);
      doc.text(lines, 22, y);
      y += lines.length * 3.6;
      for (const e of f.evidence.slice(0, 4)) {
        doc.setFontSize(7);
        doc.setTextColor(...SLATE_LIGHT);
        doc.text(`- ${e}`, 25, y);
        y += 3.4;
      }
      y += 3;
    }
    y += 2;
  }

  ensureSpace(20);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...SLATE);
  doc.text("CONTACT CHANNEL FINDINGS", 15, y);
  doc.setDrawColor(...EMERALD);
  doc.setLineWidth(0.8);
  doc.line(15, y + 1.5, 60, y + 1.5);
  y += 8;

  const sections: { title: string; rows: { display: string; status: LinkStatus; sub?: string; issue?: string | null; fix?: string | null }[] }[] = [
    {
      title: `WhatsApp links (${result.whatsappLinks.length})`,
      rows: result.whatsappLinks.map((l) => ({ display: l.url || "(no WhatsApp CTA found)", status: l.status, sub: l.phone, issue: l.issue, fix: l.suggestedFix })),
    },
    {
      title: `Phone links (${result.phoneLinks.length})`,
      rows: result.phoneLinks.map((l) => ({ display: l.url, status: l.status, sub: l.number, issue: l.issue, fix: l.suggestedFix })),
    },
    {
      title: `Email links (${result.emailLinks.length})`,
      rows: result.emailLinks.map((l) => ({ display: l.email, status: l.status, issue: l.issue, fix: l.suggestedFix })),
    },
    {
      title: `Review links (${result.reviewLinks.length})`,
      rows: result.reviewLinks.map((l) => ({ display: l.url, status: l.status, sub: l.platform })),
    },
    {
      title: `Social links (${result.socialLinks.length})`,
      rows: result.socialLinks.map((l) => ({ display: l.url, status: l.status, sub: l.platform })),
    },
  ];

  for (const section of sections) {
    if (section.rows.length === 0) continue;
    ensureSpace(14);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...SLATE);
    doc.text(section.title, 15, y);
    y += 5.5;

    const shown = section.rows.slice(0, 12);
    for (const row of shown) {
      const extra: string[] = [];
      if (row.status !== "WORKING" && row.issue) extra.push(...(doc.splitTextToSize(`Issue: ${row.issue}`, 160) as string[]));
      if (row.status !== "WORKING" && row.fix) extra.push(...(doc.splitTextToSize(`Fix: ${row.fix}`, 160) as string[]));
      ensureSpace((row.sub ? 8 : 6) + extra.length * 3.6 + 1.5);
      doc.setFontSize(7.8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 65, 85);
      const disp = doc.splitTextToSize(row.display, 118)[0] as string;
      doc.text(disp, 20, y);
      if (row.sub) {
        doc.setTextColor(...SLATE_LIGHT);
        doc.setFontSize(6.8);
        doc.text(row.sub, 20, y + 3.2);
      }
      const col = statusColor(row.status);
      doc.setFillColor(...col);
      doc.roundedRect(172, y - 3.4, 21, 4.6, 1.4, 1.4, "F");
      doc.setFontSize(6.4);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      const pill =
        row.status === "WORKING" ? "OK" : row.status === "MISSING" ? "MISSING" : "BROKEN";
      doc.text(pill, row.status === "MISSING" ? 178 : 182.5, y - 0.2, { align: "center" });
      y += row.sub ? 8 : 6;
      for (let i = 0; i < extra.length; i++) {
        doc.setFont("helvetica", i === 0 ? "bold" : "normal");
        doc.setFontSize(7);
        if (i === 0) {
          doc.setTextColor(...RED);
          doc.text(extra[i], 22, y);
        } else {
          doc.setTextColor(...EMERALD);
          doc.text(extra[i], 22, y);
        }
        y += 3.6;
      }
      y += 1;
    }
    if (section.rows.length > 12) {
      doc.setFontSize(7);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(...SLATE_LIGHT);
      doc.text(`+ ${section.rows.length - 12} more...`, 20, y);
      y += 4.5;
    }
    y += 2.5;
  }

  ensureSpace(30);
  y += 2;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...SLATE);
  doc.text("WHAT THIS MEANS FOR YOUR BUSINESS", 15, y);
  y += 7;
  const recs: string[] = [];
  const brokenW = result.whatsappLinks.filter((l) => l.status !== "WORKING").length;
  const brokenP = result.phoneLinks.filter((l) => l.status !== "WORKING").length;
  const brokenE = result.emailLinks.filter((l) => l.status !== "WORKING").length;
  if (brokenW > 0) recs.push(`${brokenW} WhatsApp link(s) are broken - customers clicking them reach a dead chat and buy elsewhere.`);
  if (brokenP > 0) recs.push(`${brokenP} phone link(s) have invalid numbers - fix the tel: numbers on your site.`);
  if (brokenE > 0) recs.push(`${brokenE} email link(s) are invalid - enquiries sent there never reach you.`);
  if (result.reviewLinks.length === 0) recs.push("No Google review links found - adding one turns happy customers into public proof.");
  if (result.security && result.security.status === "DANGER")
    recs.push("Security warning: signs of injected spam content detected. This risks a Google penalty - expert cleanup recommended.");
  recs.push(`Estimated loss: ${fmtRs(result.estimatedLoss)}/month in leads until these channels are fixed.`);
  for (const r of recs) {
    const lines = doc.splitTextToSize(r, 165) as string[];
    ensureSpace(lines.length * 4 + 3);
    doc.setFillColor(...EMERALD);
    doc.rect(15, y - 2.6, 1.6, 1.6, "F");
    doc.setFontSize(8.3);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85);
    doc.text(lines, 20, y);
    y += lines.length * 4 + 2;
  }

  ensureSpace(26);
  y += 4;
  doc.setFillColor(...SLATE);
  doc.roundedRect(15, y, 180, 18, 2.5, 2.5, "F");
  doc.setFontSize(9.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("Want this fixed in 24 hours?", 20, y + 7);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("WhatsApp us: +91 83070 70605   |   mohitsikarwar123@gmail.com", 20, y + 13);

  drawFooter(doc);
  return doc;
}

export async function downloadAuditPdf(
  url: string,
  result: ScanResult,
  opts?: { completedAt?: string }
): Promise<void> {
  const { generateAuditPdf } = await import("./pdfGenerator");
  const doc = generateAuditPdf(url, result, opts);
  const name = `leadguard-audit-${url
    .replace(/^https?:\/\//, "")
    .replace(/[^a-z0-9]/gi, "-")}.pdf`;
  doc.save(name);
}
